name: Amazon Job Radar

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browser
        run: npx playwright install --with-deps chromium

      - name: Run Amazon checker
        env:
          8759968532:AAHbTV4T3nP-HOYwetCSDAyjR9Mmy_uJz9Q: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          650824092: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node check-amazon.js
